### ISSUE TITLE
Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by sangheestyle** [sangheestyle/bigdiff-code#15]
```
UPDATED: 2013-12-04 83 items
UPDATED: 2013-12-11 90 items
Progress: 360/366 ...
UPDATED: 2013-12-17 78 items
UPDATED: 2013-12-08 93 items
{ [Error: getaddrinfo ENOTFOUND api.github.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.github.com' }
/home/sanghee/Dev/bigdiff-code/lib/github.js:179
    github.insertRepo(data['items'], function (err) {
                          ^
TypeError: Cannot read property 'items' of undefined
    at /home/sanghee/Dev/bigdiff-code/lib/github.js:179:27
    at /home/sanghee/Dev/bigdiff-code/node_modules/octonode/lib/octonode/search.js:26:18
    at Request._callback (/home/sanghee/Dev/bigdiff-code/node_modules/octonode/lib/octonode/client.js:195:20)
    at self.callback (/home/sanghee/Dev/bigdiff-code/node_modules/octonode/node_modules/request/request.js:373:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/home/sanghee/Dev/bigdiff-code/node_modules/octonode/node_modules/request/request.js:971:8)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:272:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:923:16

real    18m12.186s
user    0m12.973s
sys 0m0.640s
```

**Comment by sangheestyle** [comment]
I can't reproduce it. Don't know. When it comes once again, I will reopen this.
