### ISSUE TITLE
Errors from server during search/git

### ISSUE THREAD

**Issue by sangheestyle** [sangheestyle/bigdiff-code#22]
Problem on server

```
TypeError: undefined is not a function
   at Object.git.execCommand (/home/sangheestyle_gmail_com/dev/bigdiff-code/lib/git.js:133:16)
   at Object.git.log (/home/sangheestyle_gmail_com/dev/bigdiff-code/lib/git.js:61:21)
   at /home/sangheestyle_gmail_com/dev/bigdiff-code/index.js:42:7
   at Layer.handle [as handle_request] (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/express/lib/router/layer.js:82:5)
   at next (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/express/lib/router/route.js:91:3)
   at Layer.handle [as handle_request] (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/express/lib/router/layer.js:82:5)
   at /home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/express/lib/router/index.js:267:22
   at Function.proto.process_params (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/express/lib/router/index.js:321:12)
   at next (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/express/lib/router/index.js:261:10)
```

**Comment by sangheestyle** [comment]
sangheestyle_gmail_com@instance-1:~/dev/bigdiff-code/lib$ node --version
v0.10.36

**Comment by sangheestyle** [comment]
I have installed nvm 

https://github.com/creationix/nvm

``` shell
175  curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash
176  exec bash
177  nvm install stable
178  nvm use stable
188 nvm alias default stable
```

``` shell
sangheestyle_gmail_com@instance-1:~$ node --version
v0.12.0
```

**Comment by sangheestyle** [comment]
There has a issue.

If I use http://sangheestyle.com:8080/search/git for it, it's OK. However, if I use 80 port it's problem. I think `sudo` might make such a problem.

``` shell
$ sudo node index.js
```

This for port 80 makes problem. I think running node app on sudo may not allow to exec something with child_process due to security reason. Think about it more after demo.

I will close it now and please anybody do reopen this after this wednesday. Thanks.

**Comment by sangheestyle** [comment]
![screen shot 2015-02-24 at 1 15 14 pm](https://cloud.githubusercontent.com/assets/319490/6358214/35ba35fc-bc27-11e4-84ab-a748f80dc7c6.png)
