### ISSUE TITLE
Server: fatal: bad default revision 'HEAD'

### ISSUE THREAD

**Issue by sangheestyle** [sangheestyle/bigdiff-code#27]
Not Found in CyanogenMod/android_packages_apps_Calendarfatal: bad default revision 'HEAD'child_process.js:1382 throw err; ^Error: Command failed: git log --pretty=format:'{ "id": "%H", "author_name": "%an", "author_email": "%ae", "date": "%ad", "subject": "%s", "body": "%b"},' -G".setTag([^,|^(]_,[^,]_)" -- *.javafatal: bad default revision 'HEAD' at checkExecSyncError (child_process.js:1339:13) at execSync (child_process.js:1379:13) at Object.git.execCommand (/home/sangheestyle_gmail_com/dev/bigdiff-code/lib/git.js:148:16) at Object.git.log (/home/sangheestyle_gmail_com/dev/bigdiff-code/lib/git.js:67:21) at ReaddirpReadable.<anonymous> (/home/sangheestyle_gmail_com/dev/bigdiff-code/app.js:41:13) at ReaddirpReadable.emit (events.js:107:17) at ReaddirpReadable.<anonymous> (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:786:14) at ReaddirpReadable.emit (events.js:104:17) at emitReadable_ (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:448:10) at emitReadable (/home/sangheestyle_gmail_com/dev/bigdiff-code/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:444:5)sangheestyle_gmail_com@instance-1:~/dev/bigdiff-code$

**Comment by sangheestyle** [comment]
For workaround, I have removed entire CyanogenMod folder including their apps. I think their git usage is a little bit different so it makes some problem. This is because they don't use just `master` branch.

**Comment by sangheestyle** [comment]
This commit solve this problem.

https://github.com/sangheestyle/bigdiff-code/commit/0e07719a63eafda943c33c525f92c9ca9158679a
